In [1]:
import pandas as pd
import numpy as np
# import requests

In [2]:
# import requests
# url = 'https://raw.githubusercontent.com/krishnaik06/Stock-Sentiment-Analysis/master/Data.csv'
# res = requests.get(url, allow_redirects=True)
# with open('news_headlines.csv','wb') as file:
#     file.write(res.content)
news = pd.read_csv('news_headlines.csv', encoding = "ISO-8859-1")

In [3]:
#Knowning the data
news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    4101 non-null   object
 1   Label   4101 non-null   int64 
 2   Top1    4101 non-null   object
 3   Top2    4101 non-null   object
 4   Top3    4101 non-null   object
 5   Top4    4101 non-null   object
 6   Top5    4101 non-null   object
 7   Top6    4101 non-null   object
 8   Top7    4101 non-null   object
 9   Top8    4101 non-null   object
 10  Top9    4101 non-null   object
 11  Top10   4101 non-null   object
 12  Top11   4101 non-null   object
 13  Top12   4101 non-null   object
 14  Top13   4101 non-null   object
 15  Top14   4101 non-null   object
 16  Top15   4101 non-null   object
 17  Top16   4101 non-null   object
 18  Top17   4101 non-null   object
 19  Top18   4101 non-null   object
 20  Top19   4101 non-null   object
 21  Top20   4101 non-null   object
 22  Top21   4101 non-null   

In [ ]:
#List of numerical variables in the dataset
news.select_dtypes(exclude='object').columns[0]

In [ ]:
#List of string variables in the dataset
news.select_dtypes(include='object').columns

In [ ]:
#Checking if the data is balanced or imbalanced
(news.Label.value_counts()/len(news))*100

#### 52% of one category and  47% of another. A Balanced dataset.

In [ ]:
#Checking for Null values
news.isnull().sum()

In [ ]:
#Finding rows with Null values
news[news.isnull().any(axis=1)]

In [4]:
#Filling NA with something that does not affect learning
news.fillna(' ',inplace=True)

### Rule based train-test split 

In [5]:
train = news[news['Date'] < '2014']
test = news[news['Date'] > '2014']

In [6]:
print("Shape of training data: {} ".format(train.shape))
print("Shape of test data: {} ".format(test.shape))
print("Percentage of data used for training: {:0.2f}% ".format((train.shape[0]/len(news))*100))
print("Percentage of data used for testing: {:0.2f}% ".format((test.shape[0]/len(news))*100))

Shape of training data: (3471, 27) 
Shape of test data: (630, 27) 
Percentage of data used for training: 84.64% 
Percentage of data used for testing: 15.36% 


#### By using this rule based spliting, we got 85:15 split.

### We can first tokenize using some NLTK tokenizer and then use vectoriser of our choice.

In [ ]:
from nltk.tokenize import WordPunctTokenizer 
     
# Create a reference variable for Class WordPunctTokenizer 
tk = WordPunctTokenizer() 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the 108-year-old first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

#Using our tokenizer.
# corp=[tk.tokenize(i) for i in corpus]
# def dummy(doc):
#     return doc

vectorizer = TfidfVectorizer(ngram_range=(1,3))#,lowercase=False,preprocessor=dummy,tokenizer=dummy)
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
X.toarray()

In [7]:
train_data=train.iloc[:,2:]
label=train.iloc[:,1]

In [8]:
#Removing punctuations 
train_data.replace("[^a-zA-Z]"," ",regex=True, inplace=True)

In [9]:
#Convert the complete dataframe into lower case
train_data=train_data.apply(lambda x: x.astype(str).str.lower())

In [10]:
#Generating Corpus
headlines = []
for row in range(0,len(train_data)):
    headlines.append(' '.join(str(x) for x in train_data.iloc[row,0:25]))

In [11]:
headlines[0]

'a  hindrance to operations   extracts from the leaked reports scorecard hughes  instant hit buoys blues jack gets his skates on at ice cold alex chaos as maracana builds up for united depleted leicester prevail as elliott spoils everton s party hungry spurs sense rich pickings gunners so wide of an easy target derby raise a glass to strupar s debut double southgate strikes  leeds pay the penalty hammers hand robson a youthful lesson saints party like it s      wear wolves have turned into lambs stump mike catches testy gough s taunt langer escapes to hit     flintoff injury piles on woe for england hunters threaten jospin with new battle of the somme kohl s successor drawn into scandal the difference between men and women sara denver  nurse turned solicitor diana s landmine crusade put tories in a panic yeltsin s resignation caught opposition flat footed russian roulette sold out recovering a title'

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
## implement BAG OF WORDS
countvector=CountVectorizer(ngram_range=(2,2))
traindataset=countvector.fit_transform(headlines)

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
# implement RandomForest Classifier
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(traindataset,train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [19]:
test_data=test.iloc[:,2:]
true_y=test.iloc[:,1]

In [20]:
#Removing punctuations 
test_data.replace("[^a-zA-Z]"," ",regex=True, inplace=True)
#Convert the complete dataframe into lower case
test_data=test_data.apply(lambda x: x.astype(str).str.lower())

In [13]:
# test_transform= []
# for row in range(0,len(test.index)):
#     test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))
# test_dataset = countvector.transform(test_transform)
# predictions = randomclassifier.predict(test_dataset)

In [46]:
# ## Predict for the Test Dataset
# test_transform= []
# for row in range(0,len(test_data.index)):
#     test_transform.append(' '.join(str(x) for x in test_data.iloc[row,0:25]))
test_dataset = countvector.transform(test_transform)

In [47]:
predictions = randomclassifier.predict(test_dataset)

In [23]:
## Import library to check accuracy
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [48]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[ 42 257]
 [ 32 299]]
0.5412698412698412
              precision    recall  f1-score   support

           0       0.57      0.14      0.23       299
           1       0.54      0.90      0.67       331

    accuracy                           0.54       630
   macro avg       0.55      0.52      0.45       630
weighted avg       0.55      0.54      0.46       630



In [29]:
from sklearn.naive_bayes import MultinomialNB

In [49]:
bayes=MultinomialNB()

In [50]:
bayes.fit(traindataset,train['Label'])

MultinomialNB()

In [51]:
predictions = bayes.predict(test_dataset)

In [52]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[ 26 273]
 [ 26 305]]
0.5253968253968254
              precision    recall  f1-score   support

           0       0.50      0.09      0.15       299
           1       0.53      0.92      0.67       331

    accuracy                           0.53       630
   macro avg       0.51      0.50      0.41       630
weighted avg       0.51      0.53      0.42       630



In [59]:
np.unique(test_dataset.toarray(),return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),
 array([312140001,    139457,      4073,       388,       111,        27,
                4,         5,         4], dtype=int64))